{{- $group := .Values.groups | index .Values.group }}
{{- range .software }}
apiVersion: apps/v1
kind: DaemonSet  # Changed to DaemonSet
metadata:
  name: {{lower .type }}-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{lower .type }}  # Ensure the label matches the selector
      machine-type: {{ .type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: {{lower .type }}  # Unique labels for the pod
        machine-type: {{ .type }}  # Use the machine type for labeling
    spec:
      automountServiceAccountToken: false
      {{- if contains "PanelPC" .type }}
      nodeSelector:
        machine-type: "PanelPC"
      {{- else }}
      nodeSelector:
        machine-type: {{ .type }}
      {{- end }}

      {{- if eq .type "PanelPC-API" }}
      {{- else if eq .type "PanelPC-GUI" }}
      {{- else }}  # For all other machine types
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      {{- end }}

      hostNetwork: true  # Equivalent to --net=host
      imagePullSecrets:
      - name: regcred

      containers:
      {{- if eq .type "PanelPC-GUI" }}
      - name: panelpc-gui
        image: docker.io/flikweertvision/panelpc-gui:{{ .softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NUXT_API_URL
          value: "http://10.23.121.50:5000"
        - name: VITE_NUXT_API_URL
          value: "http://10.23.121.50:5000"
        volumeMounts:
        - name: gui-build-artifacts
          mountPath: /app/.output/
        - name: nuxt-artifacts
          mountPath: /app/.nuxt/

      {{- else if eq .type "PanelPC-API" }} # CONTAINERS FOR PANELPC API
      - name: panelpc-interface
        image: docker.io/flikweertvision/panelpc-api:{{ .softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - name: json-files
          mountPath: /home/fvt/QualityGrader/Api/json_files
        - name: images
          mountPath: /home/fvt/QualityGrader/Api/images
        - name: backup
          mountPath: /home/fvt/QualityGrader/Api/Backup
        - name: device-settings
          mountPath: /home/fvt/QualityGrader/Api/device_settings.ini
        - name: logfiles
          mountPath: /home/fvt/QualityGrader/Api/Logfiles
        - name: device-info
          mountPath: /etc/device_info.json

      {{- else }} # CONTAINERS FOR QG, SG

      - name: quality-grader
        image: docker.io/flikweertvision/quality_grader:{{ .softwareVersion }}  # Use the correct image version
        imagePullPolicy: IfNotPresent
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        securityContext:
          privileged: true  # Equivalent to --privileged
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: classifier
          mountPath: /home/nvidia/QualityGrader/classifier
        - name: detector
          mountPath: /home/nvidia/QualityGrader/detector
        - name: json-files
          mountPath: /home/nvidia/QualityGrader/json_files
        - name: data
          mountPath: /home/nvidia/QualityGrader/Data
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini
        - name: qg-device-settings
          mountPath: /home/nvidia/QualityGrader/QG_device_settings.ini
        - name: vs-device-settings
          mountPath: /home/nvidia/QualityGrader/VS_device_settings.ini
        - name: ssd
          mountPath: /home/nvidia/SSD
        - name: version-backups
          mountPath: /home/nvidia/QualityGrader/version_backups
        - name: version
          mountPath: /home/nvidia/QualityGrader/version.json
      {{- end }}
      
      {{- if eq .type "PanelPC-API" }}
      volumes:
      - name: json-files
        hostPath:
          path: /home/fvt/QualityGrader/Api/json_files
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/fvt/QualityGrader/Api/images
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /home/fvt/QualityGrader/Api/Backup
          type: DirectoryOrCreate
      - name: device-settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/device_settings.ini
          type: FileOrCreate
      - name: logfiles
        hostPath:
          path: /home/fvt/QualityGrader/Api/Logfiles
          type: DirectoryOrCreate
      - name: device-info
        hostPath:
          path: /etc/device_info.json
          type: FileOrCreate
      {{- else if eq .type "PanelPC-GUI" }}
      volumes:
      - name: gui-build-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/build
          type: DirectoryOrCreate
      - name: nuxt-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/nuxt
          type: DirectoryOrCreate
      {{- else }}
      volumes:
      - name: classifier
        hostPath:
          path: /home/nvidia/QualityGrader/classifier
          type: DirectoryOrCreate
      - name: detector
        hostPath:
          path: /home/nvidia/QualityGrader/detector
          type: DirectoryOrCreate
      - name: json-files
        hostPath:
          path: /home/nvidia/QualityGrader/json_files
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /home/nvidia/QualityGrader/Data
          type: DirectoryOrCreate
      - name: g-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/G_device_settings.ini
          type: FileOrCreate
      - name: qg-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/QG_device_settings.ini
          type: FileOrCreate
      - name: vs-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/VS_device_settings.ini
          type: FileOrCreate
      - name: ssd
        hostPath:
          path: /home/nvidia/SSD
          type: DirectoryOrCreate
      - name: version-backups
        hostPath:
          path: /home/nvidia/QualityGrader/version_backups
          type: DirectoryOrCreate
      - name: version
        hostPath:
          path: /home/nvidia/QualityGrader/version.json
          type: FileOrCreate
      - name: images
        hostPath:
          path: /home/nvidia/QualityGrader/images
          type: DirectoryOrCreate
      {{- end }}
---
{{- end }}  # End of machines range
{{- end }}  # End of group range
