{{- range .Values.clients }}

{{- range .machines }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ip }}-deployment  # Unique name for each deployment
  namespace: default
spec:
  replicas: 1  # Ensures only one instance per machine
  strategy:
    type: RollingUpdate  # Enable rolling updates
    rollingUpdate:
      maxUnavailable: 1  # Control the number of pods that can be unavailable during an update
  selector:
    matchLabels:
      app: {{ .type }}-{{ .ip }}  # Ensure the label matches the selector
      machine-type: {{ .type }}
  template:
    metadata:
      labels:
        app: {{ .type }}-{{ .ip }}  # Unique labels for the pod
        machine-type: {{ .type }}  # Use the machine type for labeling
    spec:
      automountServiceAccountToken: false
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: machine_ip
                    operator: In
                    values:
                      - {{ .ip }}  # Use each machine's IP
      
      {{- if eq .type "PanelPC" }}
      {{- else }}  # For all other machine types
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      {{- end }}
        
      hostNetwork: true  # Equivalent to --net=host
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      containers:
      
      {{- if eq .type "PanelPC" }}  # Check if machine type is PanelPC
      - name: panel-pc-gui
        image: docker.io/flikweertvision/panelpc-gui:1.0.3
        securityContext:
          privileged: true
        ports:
        - containerPort: 3000
        env:
        - name: NUXT_API_URL
          value: "http://10.23.121.50:5000"
        - name: VITE_NUXT_API_URL
          value: "http://10.23.121.50:5000"
      - name: panelpc-interface
        image: docker.io/flikweertvision/panelpc-api:1.6.1-api
        securityContext:
          privileged: true
        hostNetwork: true
        volumeMounts:
        - name: json-files
          mountPath: /home/fvt/QualityGrader/Api/json_files
        - name: images
          mountPath: /home/fvt/QualityGrader/Api/images
        - name: backup
          mountPath: /home/fvt/QualityGrader/Api/Backup
        - name: device-settings
          mountPath: /home/fvt/QualityGrader/Api/device_settings.ini
        - name: settings
          mountPath: /home/fvt/QualityGrader/Api/settings.ini
        - name: logfiles
          mountPath: /home/fvt/QualityGrader/Api/Logfiles
        - name: device-info
          mountPath: /etc/device_info.json
     
      {{- else }}  # For all other machine types

      - name: quality-grader
        image: docker.io/flikweertvision/quality_grader:{{ .softwareVersion }}  # Use the correct image version
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        securityContext:
          privileged: true  # Equivalent to --privileged
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: classifier
          mountPath: /home/nvidia/QualityGrader/classifier
        - name: detector
          mountPath: /home/nvidia/QualityGrader/detector
        - name: json-files
          mountPath: /home/nvidia/QualityGrader/json_files
        - name: data
          mountPath: /home/nvidia/QualityGrader/Data
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini
        - name: qg-device-settings
          mountPath: /home/nvidia/QualityGrader/QG_device_settings.ini
        - name: vs-device-settings
          mountPath: /home/nvidia/QualityGrader/VS_device_settings.ini
        - name: settings
          mountPath: /home/nvidia/QualityGrader/settings.ini
        - name: ssd
          mountPath: /home/nvidia/SSD
      {{- end }}
      
      {{- if eq .type "PanelPC" }}
      volumes:
      - name: json-files
        hostPath:
          path: /home/fvt/QualityGrader/Api/json_files
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/fvt/QualityGrader/Api/images
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /home/fvt/QualityGrader/Api/Backup
          type: DirectoryOrCreate
      - name: device-settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/device_settings.ini
          type: FileOrCreate
      - name: settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/settings.ini
          type: FileOrCreate
      - name: logfiles
        hostPath:
          path: /home/fvt/QualityGrader/Api/Logfiles
          type: DirectoryOrCreate
      - name: device-info
        hostPath:
          path: /etc/device_info.json
          type: FileOrCreate
      {{- else }}
      volumes:
      - name: classifier
        hostPath:
          path: /home/nvidia/QualityGrader/classifier
          type: DirectoryOrCreate
      - name: detector
        hostPath:
          path: /home/nvidia/QualityGrader/detector
          type: DirectoryOrCreate
      - name: json-files
        hostPath:
          path: /home/nvidia/QualityGrader/json_files
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /home/nvidia/QualityGrader/Data
          type: DirectoryOrCreate
      - name: g-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/G_device_settings.ini
          type: FileOrCreate
      - name: qg-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/QG_device_settings.ini
          type: FileOrCreate
      - name: vs-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/VS_device_settings.ini
          type: FileOrCreate
      - name: settings
        hostPath:
          path: /home/nvidia/QualityGrader/settings.ini
          type: FileOrCreate
      - name: ssd
        hostPath:
          path: /home/nvidia/SSD
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/nvidia/QualityGrader/images
          type: DirectoryOrCreate
      {{- end }}
---
{{- end }}  # End of machines range
{{- end }}  # End of clients range
