apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: docker-registry
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels: { app: docker-registry }
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels: { app: docker-registry }
    spec:
      nodeSelector:
        machine-type: "PanelPC"

      volumes:
      - name: regcred
        secret:
          secretName: regcred
      - name: registry-data
        hostPath:
          path: /opt/registry
          type: DirectoryOrCreate
      - name: client_crt
        hostPath: 
          path: /var/lib/rancher/k3s/server/tls/client-ca.crt
          type: File
      - name: client_key
        hostPath: 
          path: /var/lib/rancher/k3s/server/tls/client-ca.key
          type: File
      - name: registry-config
        emptyDir: {}

      initContainers:
      - name: build-config
        image: busybox:1.36
        volumeMounts:
        - { name: regcred, mountPath: /reg, readOnly: true }
        - { name: registry-config, mountPath: /cfg }
        command: ["/bin/sh","-c"]
        args:
        - |
          user=$(sed -n 's/.*"username":[[:space:]]*"\([^"]*\)".*/\1/p' /reg/.dockerconfigjson | head -n1)
          pass=$(sed -n 's/.*"password":[[:space:]]*"\([^"]*\)".*/\1/p' /reg/.dockerconfigjson | head -n1)
          cat > /cfg/config.yml <<EOF
          version: 0.1
          log:
            level: info
          storage:
            filesystem:
              rootdirectory: /var/lib/registry
          http:
            addr: :5233
            tls:
              certificate: /var/lib/rancher/k3s/server/tls/client-ca.crt
              key: /var/lib/rancher/k3s/server/tls/client-ca.key
          proxy:
            remoteurl: https://registry-1.docker.io
            username: $user
            password: $pass
          EOF

      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5233
          hostPort: 5233
        volumeMounts:
        - { name: registry-data,   mountPath: /var/lib/registry }
        - { name: registry-config, mountPath: /etc/docker/registry, readOnly: true }
        - { name: client_crt, mountPath: /var/lib/rancher/k3s/server/tls/client-ca.crt, readOnly: true }
        - { name: client_key, mountPath: /var/lib/rancher/k3s/server/tls/client-ca.key, readOnly: true }
        args: ["/etc/docker/registry/config.yml"]

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: docker-registry
#   namespace: default
# spec:
#   selector: { app: docker-registry }
#   ports:
#   - name: https
#     port: 5233
#     targetPort: 5233
