{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "DV" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet  # Changed to DaemonSet
metadata:
  name: {{lower $software_type }}-program-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
      machine-type: {{ $software_type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
        machine-type: {{ $software_type }}  # Use the machine type for labeling
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: {{ $software_type }}
      
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

      imagePullSecrets:
      - name: regcred
      
      hostNetwork: true
      
      containers:
      - name: quality-grader
        image: docker.io/flikweertvision/quality_grader-divider:{{ $software.softwareVersion }}  # Use the correct image version
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "-c"]
        args: 
        - "sleep 10 && exec supervisord -c /home/nvidia/QualityGrader/supervisord.conf -n"
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        securityContext:
          privileged: true  # Equivalent to --privileged
        livenessProbe:
          httpGet:
            path: /machine_status_monitorings_systeem
            port: 5001
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: classifier
          mountPath: /home/nvidia/QualityGrader/classifier
        - name: detector
          mountPath: /home/nvidia/QualityGrader/detector
        - name: json-files
          mountPath: /home/nvidia/QualityGrader/json_files
        - name: data
          mountPath: /home/nvidia/QualityGrader/Data
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini
        - name: sg-device-settings
          mountPath: /home/nvidia/QualityGrader/SG_device_settings.ini
        - name: ssd
          mountPath: /home/nvidia/SSD
        - name: version-backups
          mountPath: /home/nvidia/QualityGrader/version_backups
        - name: version
          mountPath: /home/nvidia/QualityGrader/version.json
        - name: images
          mountPath: /home/nvidia/QualityGrader/images
        - name: logfiles
          mountPath: /etc/fvt_logfiles
        - name: timezone-settings
          mountPath: /etc/timezone

      initContainers:
      - name: plc-tool
        image: docker.io/flikweertvision/plc_deploy_backup:{{ $plc.softwareVersion }}
        volumeMounts:
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini

      volumes:
      - name: classifier
        hostPath:
          path: /home/nvidia/QualityGrader/classifier
          type: DirectoryOrCreate
      - name: detector
        hostPath:
          path: /home/nvidia/QualityGrader/detector
          type: DirectoryOrCreate
      - name: json-files
        hostPath:
          path: /home/nvidia/QualityGrader/json_files
          type: DirectoryOrCreate
      - name: data
        hostPath:
          path: /home/nvidia/QualityGrader/Data
          type: DirectoryOrCreate
      - name: g-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/G_device_settings.ini
          type: FileOrCreate
      - name: sg-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/SG_device_settings.ini
          type: FileOrCreate
      - name: ssd
        hostPath:
          path: /home/nvidia/SSD
          type: DirectoryOrCreate
      - name: version-backups
        hostPath:
          path: /home/nvidia/QualityGrader/version_backups
          type: DirectoryOrCreate
      - name: version
        hostPath:
          path: /home/nvidia/QualityGrader/version.json
          type: FileOrCreate
      - name: images
        hostPath:
          path: /home/nvidia/QualityGrader/images
          type: DirectoryOrCreate
      - name: logfiles
        hostPath:
          path: /etc/fvt_logfiles
          type: DirectoryOrCreate
      - name: timezone-settings
        hostPath:
          path: /etc/timezone
          type: FileOrCreate
{{- end }}
