{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Fv-Producer" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: {{lower $software_type }}-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
      machine-type: {{ $software_type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false

      imagePullSecrets:
      - name: regcred

      hostNetwork: true  # Equivalent to --net=host

      containers:
      - name: fv-producer
        image: docker.io/flikweertvision/fv-producer:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true  # Equivalent to --privileged
        env:
        - name: RMQ_URL
          value: "amqp://guest:guest@10.10.4.10:5672/"
        volumeMounts:
        - name: quality-grader-home
          mountPath: /home/nvidia/QualityGrader
          readOnly: true
        - name: quality-grader-etc-fv
          mountPath: /etc/fv
          readOnly: false

      volumes:
      - name: quality-grader-home
        hostPath:
          path: /home/nvidia/QualityGrader
          type: Directory
      - name: quality-grader-etc-fv
        hostPath:
          path: /etc/fv
          type: Directory
          
{{- end }}
