{{- $group := .Values.group | index .Values.groups }}
{{- $machineTypes := list "QG" "DV" }} # Define supported machine types

{{- range $machineType := $machineTypes }}
  {{- if hasKey $group.software $machineType }} # Ensure the software exists before processing
    {{- $software := index $group.software $machineType }}
---
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-{{ lower $machineType }}
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/quality_grader:{{ $software.softwareVersion }}
  parallelism: 5
  selector:
    matchLabels:
      machine-type: {{ $machineType }}
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 5
    timeoutSeconds: 300
  {{- end }}
{{- end }}

{{- $panelPCAPI := index $group.software "PanelPC-API" | default dict }}
{{- $panelPCGUI := index $group.software "PanelPC-GUI" | default dict }}

{{- if $panelPCAPI.softwareVersion }}
---
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-panelpc-api
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/panelpc-api:{{ $panelPCAPI.softwareVersion }}
  parallelism: 5
  selector:
    matchLabels:
      machine-type: PanelPC
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 5
    timeoutSeconds: 300
{{- end }}

{{- if $panelPCGUI.softwareVersion }}
---
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-panelpc-gui
  namespace: default
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/panelpc-gui:{{ $panelPCGUI.softwareVersion }}
  parallelism: 5
  selector:
    matchLabels:
      machine-type: PanelPC
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 5
    timeoutSeconds: 300
{{- end }}