{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Messaging-App" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: {{lower $software_type }}-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
    spec:
      automountServiceAccountToken: true

      hostNetwork: true  # Equivalent to --net=host
      imagePullSecrets:
      - name: regcred

      containers:
      - name: messaging-app
        image: docker.io/flikweertvision/msg-app-excercise:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_NAME
            valueFrom:
              fieldRef:
                fieldPath: {{lower $software_type }}-software-daemonset
        volumeMounts:
        - name: kube-config
          mountPath: /etc/rancher/k3s/k3s.yaml
          readOnly: true

      volumes:
      - name: kube-config
        hostPath:
          path: /etc/rancher/k3s/k3s.yaml
          type: File
          
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io