{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Messaging-App" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: {{lower $software_type }}-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
    spec:
      automountServiceAccountToken: true

      imagePullSecrets:
      - name: regcred

      containers:
      - name: messaging-app
        image: docker.io/flikweertvision/msg-app-excercise:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true  # Equivalent to --privileged
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: APP_NAME
            value: {{lower $software_type }}
          
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{lower $software_type }}-software-service
spec:
  type: ClusterIP
  selector:
    app: {{lower $software_type }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: {{lower $software_type }}-software-service-headless
spec:
  clusterIP: None
  selector:
    app: {{lower $software_type }}
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reader-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-reader-role
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: reader-role
  apiGroup: rbac.authorization.k8s.io