{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Plc-Tool" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: Daemonset
metadata:
  name: plc-tool-software-daemonset
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
      machine-type: {{ $software_type }}
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
        machine-type: {{ $software_type }} 
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        machine-type: "QG"
      hostNetwork: true
      containers:
      - name: quality-grader
        image: docker.io/flikweertvision/plc_deploy_backup:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini
      volumes:
      - name: g-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/G_device_settings.ini
          type: FileOrCreate

      restartPolicy: Never
{{- end }}
