{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Plc-Tool" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: batch/v1
kind: Job
metadata:
  name: plc-tool-software-job
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        machine-type: "QG"
      hostNetwork: true
      containers:
      - name: quality-grader
        image: docker.io/flikweertvision/plc_deploy_backup:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: g-device-settings
          mountPath: /home/nvidia/QualityGrader/G_device_settings.ini
      volumes:
      - name: g-device-settings
        hostPath:
          path: /home/nvidia/QualityGrader/G_device_settings.ini
          type: FileOrCreate

      restartPolicy: Never
{{- end }}
