{{- $group := index .Values.groups .Values.group }}
{{- $software_type := "PanelPC-API" }}
{{- $software := index $group.software $software_type }}
{{- $isDV := eq ($group.type | default "") "DV" }}
{{- if and $software (or $isDV) }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet  # Changed to DaemonSet
metadata:
  name: {{lower $software_type }}-pp-api-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
      machine-type: {{ $software_type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{ lower $software_type }}
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: "PanelPC"

      hostNetwork: true  # Equivalent to --net=host
      imagePullSecrets:
      - name: regcred
      containers:
      - name: panelpc-interface
        image: docker.io/flikweertvision/panelpc-api-divider:{{ $software.softwareVersion }}
        command: ["/bin/bash", "-c"]
        args: 
        - "sleep 10 && exec supervisord -c /home/fvt/QualityGrader/Api/supervisord.conf -n"
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /machines
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: json-files
          mountPath: /home/fvt/QualityGrader/Api/json_files
        - name: images
          mountPath: /home/fvt/QualityGrader/Api/images
        - name: backup
          mountPath: /home/fvt/QualityGrader/Api/Backup
        - name: device-settings
          mountPath: /home/fvt/QualityGrader/Api/device_settings.ini
        - name: logfiles
          mountPath: /home/fvt/QualityGrader/Api/Logfiles
        - name: device-info
          mountPath: /etc/device_info.json
        - name: version
          mountPath: /home/fvt/QualityGrader/Api/version.json
        - name: version-backups
          mountPath: /home/fvt/QualityGrader/Api/version_backups
      volumes:
      - name: json-files
        hostPath:
          path: /home/fvt/QualityGrader/Api/json_files
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/fvt/QualityGrader/Api/images
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /home/fvt/QualityGrader/Api/Backup
          type: DirectoryOrCreate
      - name: device-settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/device_settings.ini
          type: FileOrCreate
      - name: logfiles
        hostPath:
          path: /home/fvt/QualityGrader/Api/Logfiles
          type: DirectoryOrCreate
      - name: device-info
        hostPath:
          path: /etc/device_info.json
          type: FileOrCreate
      - name: version
        hostPath:
          path: /home/fvt/QualityGrader/Api/version.json
          type: FileOrCreate
      - name: version-backups
        hostPath:
          path: /home/fvt/QualityGrader/Api/version_backups
          type: DirectoryOrCreate
{{- end }}
