{{- $url := .Values.endpoint }}
{{- $ipRegex := `[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+` }}
{{- $panelpc_ip := regexFind $ipRegex $url }}

{{- $group := index .Values.groups .Values.group }}
{{- $software_type := "PanelPC-GUI" }}
{{- $software := index $group.software $software_type }}
{{- $isQG := eq ($group.type | default "") "QG" }}
{{- $isDV := eq ($group.type | default "") "DV" }}
{{- if and $software (or $isQG $isDV) }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: {{ lower $software_type }}-pp-gui-software-daemonset
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{ lower $software_type }}
      machine-type: {{ $software_type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{ lower $software_type }}
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: "PanelPC"
      hostNetwork: true
      imagePullSecrets:
        - name: regcred
      terminationGracePeriodSeconds: 5
      containers:
        - name: panelpc-gui
          image: docker.io/flikweertvision/{{ ternary "panelpc-gui" "panelpc-gui-divider" $isQG }}:{{ $software.softwareVersion }}
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
{{- if $isQG }}
            - name: NUXT_API_BASE
              value: "http://{{ $panelpc_ip }}:5000"
            - name: NUXT_PUBLIC_CALIBRATION_TOOL_URL
              value: "http://{{ $panelpc_ip }}:5123"
{{- end }}
{{- if $isDV }}
            - name: NUXT_PUBLIC_API_URL
              value: "http://{{ $panelpc_ip }}:5000"
            - name: CALIBRATION_TOOL_URL
              value: "http://{{ $panelpc_ip }}:5123"
{{- end }}
          volumeMounts:
            - name: timezone-settings
              mountPath: /etc/timezone
              readOnly: true
{{- if $isDV }}
            - name: gui-build-artifacts
              mountPath: /app/.output/
            - name: nuxt-artifacts
              mountPath: /app/.nuxt/
{{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 15
      volumes:
        - name: timezone-settings
          hostPath:
            path: /etc/timezone
            type: FileOrCreate
{{- if $isDV }}
        - name: gui-build-artifacts
          hostPath:
            path: /home/fvt/QualityGrader/UI/build
            type: DirectoryOrCreate
        - name: nuxt-artifacts
          hostPath:
            path: /home/fvt/QualityGrader/UI/nuxt
            type: DirectoryOrCreate
{{- end }}
{{- end }}
