{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "PanelPC-API" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps/v1
kind: Deployment  # Changed from DaemonSet to Deployment
metadata:
  name: {{lower $software_type }}-pp-api-software-deployment  # Updated name to reflect Deployment type
  namespace: default
spec:
  replicas: 1  # Added replica count, adjust as needed
  selector:
    matchLabels:
      app: {{lower $software_type }}
      machine-type: {{ $software_type }}
  strategy:  # Replaced updateStrategy with strategy
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{lower $software_type }}
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: "PanelPC"
      hostNetwork: true  # Review if necessary for Deployment
      imagePullSecrets:
      - name: regcred
      containers:
      - name: panelpc-interface
        image: docker.io/flikweertvision/panelpc-api:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /machines
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: json-files
          mountPath: /home/fvt/QualityGrader/Api/json_files
        - name: images
          mountPath: /home/fvt/QualityGrader/Api/images
        - name: backup
          mountPath: /home/fvt/QualityGrader/Api/Backup
        - name: device-settings
          mountPath: /home/fvt/QualityGrader/Api/device_settings.ini
        - name: logfiles
          mountPath: /home/fvt/QualityGrader/Api/Logfiles
        - name: device-info
          mountPath: /etc/device_info.json
      volumes:
      - name: json-files
        hostPath:
          path: /home/fvt/QualityGrader/Api/json_files
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/fvt/QualityGrader/Api/images
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /home/fvt/QualityGrader/Api/Backup
          type: DirectoryOrCreate
      - name: device-settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/device_settings.ini
          type: FileOrCreate
      - name: logfiles
        hostPath:
          path: /home/fvt/QualityGrader/Api/Logfiles
          type: DirectoryOrCreate
      - name: device-info
        hostPath:
          path: /etc/device_info.json
          type: FileOrCreate
{{- end }}
