{{- $group := .Values.group | index .Values.groups }}
{{- range $group.software }}
apiVersion: apps/v1
kind: DaemonSet  # Changed to DaemonSet
metadata:
  name: {{lower .type }}-pp-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{lower .type }}  # Ensure the label matches the selector
      machine-type: {{ .type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        app: {{lower .type }}  # Unique labels for the pod
        machine-type: {{ .type }}  # Use the machine type for labeling
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: "PanelPC"

      hostNetwork: true  # Equivalent to --net=host
      imagePullSecrets:
      - name: regcred

      containers:
      {{- if eq .type "PanelPC-GUI" }}
      - name: panelpc-gui
        image: docker.io/flikweertvision/panelpc-gui:{{ .softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NUXT_API_URL
          value: "http://10.23.121.50:5000"
        - name: VITE_NUXT_API_URL
          value: "http://10.23.121.50:5000"
        volumeMounts:
        - name: gui-build-artifacts
          mountPath: /app/.output/
        - name: nuxt-artifacts
          mountPath: /app/.nuxt/
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15

      {{- else if eq .type "PanelPC-API" }} # CONTAINERS FOR PANELPC API
      - name: panelpc-interface
        image: docker.io/flikweertvision/panelpc-api:{{ .softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        livenessProbe:
          httpGet:
            path: /machines
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 15
        volumeMounts:
        - name: json-files
          mountPath: /home/fvt/QualityGrader/Api/json_files
        - name: images
          mountPath: /home/fvt/QualityGrader/Api/images
        - name: backup
          mountPath: /home/fvt/QualityGrader/Api/Backup
        - name: device-settings
          mountPath: /home/fvt/QualityGrader/Api/device_settings.ini
        - name: logfiles
          mountPath: /home/fvt/QualityGrader/Api/Logfiles
        - name: device-info
          mountPath: /etc/device_info.json
      {{- end }}
      
      {{- if eq .type "PanelPC-API" }}
      volumes:
      - name: json-files
        hostPath:
          path: /home/fvt/QualityGrader/Api/json_files
          type: DirectoryOrCreate
      - name: images
        hostPath:
          path: /home/fvt/QualityGrader/Api/images
          type: DirectoryOrCreate
      - name: backup
        hostPath:
          path: /home/fvt/QualityGrader/Api/Backup
          type: DirectoryOrCreate
      - name: device-settings
        hostPath:
          path: /home/fvt/QualityGrader/Api/device_settings.ini
          type: FileOrCreate
      - name: logfiles
        hostPath:
          path: /home/fvt/QualityGrader/Api/Logfiles
          type: DirectoryOrCreate
      - name: device-info
        hostPath:
          path: /etc/device_info.json
          type: FileOrCreate
      {{- else if eq .type "PanelPC-GUI" }}
      volumes:
      - name: gui-build-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/build
          type: DirectoryOrCreate
      - name: nuxt-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/nuxt
          type: DirectoryOrCreate
      {{- end }}
---
{{- end }}  # End of machines range
