{{- $url := .Values.endpoint }}
{{- $ipRegex := `[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+` }}
{{- $panelpc_ip := regexFind $ipRegex $url }}

{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "PanelPC-GUI" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps/v1
kind: Deployment  # Changed from DaemonSet to Deployment
metadata:
  name: {{lower $software_type }}-pp-gui-software-deployment  # Updated name to reflect Deployment type
  namespace: default
spec:
  replicas: 1  # Added replica count, adjust as needed
  selector:
    matchLabels:
      app: {{lower $software_type }}
      machine-type: {{ $software_type }}
  strategy:  # Replaced updateStrategy with strategy
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: {{lower $software_type }}
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: "PanelPC"
      hostNetwork: true  # Review if necessary for Deployment
      imagePullSecrets:
      - name: regcred
      containers:
      - name: panelpc-gui
        image: docker.io/flikweertvision/panelpc-gui:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: NUXT_PUBLIC_API_URL
          value: "http://{{ $panelpc_ip }}:5000"
        volumeMounts:
        - name: gui-build-artifacts
          mountPath: /app/.output/
        - name: nuxt-artifacts
          mountPath: /app/.nuxt/
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 15
      volumes:
      - name: gui-build-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/build
          type: DirectoryOrCreate
      - name: nuxt-artifacts
        hostPath:
          path: /home/fvt/QualityGrader/UI/nuxt
          type: DirectoryOrCreate
{{- end }}
