{{- $group := .Values.group | index .Values.groups }}
{{- range $softwareType, $software := $group.software }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ lower $softwareType }}-prepuller
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector:
    matchLabels:
      app: {{ lower $softwareType }}-prepuller
  template:
    metadata:
      labels:
        app: {{ lower $softwareType }}-prepuller
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: {{ $softwareType }}  # You can change or remove this to run on all nodes
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ lower $softwareType }}-prepuller
        image: docker.io/alpine:3.21
        imagePullPolicy: IfNotPresent
{{- end }}
