{{- $url := .Values.endpoint }}
{{- $ipRegex := `[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+` }}
{{- $panelpc_ip := regexFind $ipRegex $url }}

apiVersion: batch/v1
kind: Job
metadata:
  name: node_indexer
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: panel-pc-service-account  # Ensure proper permissions
      containers:
        - name: node_indexer
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
                # Step 1: Dynamically create a values override for replicaCount
                WORKER_NODES=$(sudo k3s kubectl get nodes -l node-role.kubernetes.io/worker --no-headers | wc -l)
                if [[ "$WORKER_NODES" -eq 0 ]]; then
                  echo "No worker nodes detected. Aborting deployment."
                  exit 1
                fi

                echo "replicaCount: $WORKER_NODES" > /workdir/dynamic-values.yaml
      volumes:
        - name: workdir
          emptyDir: {}
      restartPolicy: Never
