{{- $group := .Values.group | index .Values.groups }}
{{- $qgSoftware := $group.software.QG }}
{{- $panelPCAPI := index $group.software "PanelPC_API" }}
{{- $panelPCGUI := index $group.software "PanelPC_GUI" }}

apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-qg
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/quality_grader:{{ $qgSoftware.softwareVersion }}
  selector:
    matchLabels:
      machine_type: QG # Select all nodes labeled machine_type=QG
  parallelism: 5 # Controls how many nodes pull the image simultaneously
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 3
    timeoutSeconds: 300

---
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-panelpc-api
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/panelpc-api:{{ $panelPCAPI.softwareVersion }}
  selector:
    matchLabels:
      machine_type: PanelPC # Select all nodes labeled machine_type=PanelPC-API
  parallelism: 5
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 3
    timeoutSeconds: 300

---
apiVersion: apps.kruise.io/v1alpha1
kind: ImagePullJob
metadata:
  name: pre-pull-image-panelpc-gui
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  pullSecrets:
  - regcred
  image: docker.io/flikweertvision/panelpc-gui:{{ $panelPCGUI.softwareVersion }}
  selector:
    matchLabels:
      machine_type: PanelPC # Select all nodes labeled machine_type=PanelPC-GUI
  parallelism: 5
  completionPolicy:
    type: Always
    activeDeadlineSeconds: 3000
    ttlSecondsAfterFinished: 300
  pullPolicy:
    backoffLimit: 3
    timeoutSeconds: 300
