{{- $group := .Values.group | index .Values.groups }}
{{- range $softwareType, $software := $group.software }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ lower $softwareType }}-prepuller
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector:
    matchLabels:
      name: {{ lower $softwareType }}-prepuller
  template:
    metadata:
      labels:
        name: {{ lower $softwareType }}-prepuller
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: {{ $softwareType }}
      imagePullSecrets:
      - name: regcred
      # Configure an init container for the image to be pulled
      initContainers:
        - name: {{ lower $softwareType }}-prepuller
          image: docker.io/flikweertvision/quality_grader:{{ $software.softwareVersion }}
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "echo 'Image pulled for {{ $softwareType }} with version {{ $software.softwareVersion }}'"]

      # Use the pause container to keep the pod alive until the hook completes
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
          resources:
            limits:
              cpu: 1m
              memory: 8Mi
            requests:
              cpu: 1m
              memory: 8Mi
{{- end }}
