apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-presync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: presync
          image: busybox  # Use a lightweight image with basic tools (if you don't have custom images)
          command:
            - /bin/sh
            - -c
            - |
              # Step 1: Check if current time is after 11 AM
              current_hour=$(date +'%H')
              if [ "$current_hour" -lt 10 ]; then
                echo "It is before 10 AM. Skipping sync."
                exit 1
              fi

              # Step 2: Use nc (netcat) to check if the machine status endpoint is available
              endpoint="10.23.121.50"
              port="5000"
              # Attempt to check if the endpoint is reachable by sending an HTTP request
              response=$(echo "GET /machine_status_monitorings_systeem HTTP/1.1\r\nHost: $endpoint\r\n\r\n" | nc -w 5 $endpoint $port)

              # Step 3: If the endpoint is not reachable (response is empty), allow the sync
              if [ -z "$response" ]; then
                echo "Endpoint $endpoint is not reachable. Allowing sync to proceed."
                exit 0
              fi

              # Step 4: If the response is available, check if it contains the expected values for QG_active and VS_active
              if echo "$response" | grep -q '"QG_active":false' && echo "$response" | grep -q '"VS_active":false'; then
                echo "Machine status is as expected."
              else
                echo "Machine status is not as expected. QG_active or VS_active is not false."
                exit 1
              fi

              echo "Machine is in the correct state and time is after 11 AM. Proceeding with sync."
