apiVersion: batch/v1
kind: Job
metadata:
  name: machine-status-check
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: machine-status-check
          image: alpine/curl:latest
          command:
            - /bin/sh
            - -c
            - |
                # Step 1: Check if current time is after 8 AM
                current_hour=$(date +'%H')
                echo "Current hour: $current_hour"
                if [ "$current_hour" -lt 8 ]; then
                  echo "It is before 8 AM. Skipping sync."
                  exit 1
                fi

                # Step 2: Check if the machine status endpoint is reachable
                endpoint="{{server}}"
                port="5000"
                response=$(curl -s --max-time 10 "http://$endpoint:$port/machine_status_monitorings_systeem")

                if [ $? -ne 0 ]; then
                  echo "Endpoint $endpoint is not reachable. Allowing sync to proceed."
                  exit 0
                fi

                # Step 3: Parse the response and check machine status
                echo "Response from endpoint: $response"
                if echo "$response" | grep -q '"QG_active":true' || echo "$response" | grep -q '"VS_active":true'; then
                  echo "Machine status is not as expected."
                  exit 1
                else
                  echo "Machine status is as expected."
                fi
      restartPolicy: Never
