{{- $group := .Values.group | index .Values.groups }}
{{- range $softwareType, $software := $group.software }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ lower $softwareType }}-prepuller
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector:
    matchLabels:
      name: {{ lower $softwareType }}-prepuller
  template:
    metadata:
      labels:
        name: {{ lower $softwareType }}-prepuller
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        machine-type: {{ $softwareType }}
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ lower $softwareType }}-prepuller
        image: docker.io/alpine:3.21
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'Pulling image for {{ $softwareType }} with version {{ $software.softwareVersion }}'; exit 0"]
{{- end }}
