{{- $url := .Values.endpoint }}
{{- $ipRegex := `[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+` }}
{{- $machineIp := regexFind $ipRegex $url }}

{{- $softwareVersion := .Values.Version }}

{{- $group := .Values.group | index .Values.groups }}
{{- $software_type := "Telemetry-Producer" }}
{{- $software := $software_type | index $group.software}}
{{- if $software }}
apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: {{lower $software_type }}-software-daemonset  # Updated name to reflect the DaemonSet type
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    apps.kruise.io/image-predownload-parallelism: "10"
spec:
  selector:
    matchLabels:
      app: {{lower $software_type }}  # Ensure the label matches the selector
      machine-type: {{ $software_type }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
      rollingUpdateType: Standard
  template:
    metadata:
      labels:
        app: {{lower $software_type }}  # Unique labels for the pod
        machine-type: {{ $software_type }}
    spec:
      automountServiceAccountToken: false

      imagePullSecrets:
      - name: regcred

      hostNetwork: true  # Equivalent to --net=host

      containers:
      - name: telemetry-producer
        image: docker.io/flikweertvision/fv-producer:{{ $software.softwareVersion }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
        - name: MACHINE_IP
          value: {{ $machineIp }}
        - name: SOFTWARE_VERSION
          value: {{ $softwareVersion }}
        volumeMounts:
        - name: quality-grader-home
          mountPath: /home
          readOnly: true

      volumes:
      - name: quality-grader-home
        hostPath:
          path: /home
          type: Directory
          
{{- end }}
