groups:
  production:
    software:
      QG:
        softwareVersion: "v1.8.2-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.1-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  production_plc:
    software:
      QG:
        softwareVersion: "v1.8.2-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.1-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "QG_V2.4.6_SP18"
  divider:
    software:
      DV:
        softwareVersion: "DV_dev_DV-fixed-button-docker-orin"
      PanelPC-API:
        softwareVersion: "dev_divider_fix"
      PanelPC-GUI:
        softwareVersion: "dev_combined-interface-docker"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  multi-model:
    software:
      QG:
        softwareVersion: "v1.8.2-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.1-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  vs-flipper-test:
    software:
      QG:
        softwareVersion: "dev_vs_flipper_tests-orin"
      PanelPC-API:
        softwareVersion: "v1.7.7-api"
      PanelPC-GUI:
        softwareVersion: "dev_2.3.0-server_calibration-tool-shortcut"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  service-round-xavier-swap:
    software:
      QG:
        softwareVersion: "v1.7.9-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.7.7-api"
      PanelPC-GUI:
        softwareVersion: "dev_2.3.0-server_calibration-tool-shortcut"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  production-europe:
    software:
      QG:
        softwareVersion: "v1.8.3-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.2-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.2-server"
      Calibration-Tool:
        softwareVersion: "v0.2.63"
      Plc-Tool:
        softwareVersion: "empty"
  production-asian-oceania:
    software:
      QG:
        softwareVersion: "v1.8.2-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.1-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  production-americas:
    software:
      QG:
        softwareVersion: "v1.8.2-pc-orin"
      PanelPC-API:
        softwareVersion: "v1.8.1-api"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
  added-sensors-test:
    software:
      QG:
        softwareVersion: "dev_MD-315_added-sensors-with-status-33-orin"
      PanelPC-API:
        softwareVersion: "dev_add-error-33"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "QG_V2.4.7_SP18"
  added-sensors-agroduiv-test:
    software:
      QG:
        softwareVersion: "dev_MD-315_added-sensors-with-status-33-orin"
      PanelPC-API:
        softwareVersion: "dev_add-error-33"
      PanelPC-GUI:
        softwareVersion: "v2.4.1-server"
      Calibration-Tool:
        softwareVersion: "v0.2.51"
      Plc-Tool:
        softwareVersion: "empty"
