clients:
  - name: test-linux1
    subnet: 10.23.254.0/24
    software:
      - type: QG
        softwareVersion: "1.6.4-pc-orin"
        jetsonType: "orin"
  - name: flikweertintern
    subnet: 10.23.121.0/24
    software:
      - type: QG
        softwareVersion: "1.6.5-pc_belt_speed_demo-orin"
        jetsonType: "orin"
      - type: PanelPC-API
        softwareVersion: "1.6.2-api_belt-speed-settings-interface"
      - type: PanelPC-GUI
        softwareVersion: "1.0.3"
